[pytest]
addopts = -vs -n auto --reruns 2 --alluredir ./allure-results
testpaths = ./tests
python_files = test_*.py

log_cli = true
log_cli_level = INFO
log_cli_format = [%(asctime)s] [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S

log_allure_print = true
allure_log_level = INFO
log_format = %(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S